2021-05-28 12:08:20,214 ERROR: Exception on /index [GET] [in /home/benc/Workspaces/microblog/.venv-microblog/lib/python3.8/site-packages/flask/app.py:1440]
Traceback (most recent call last):
  File "/home/benc/Workspaces/microblog/.venv-microblog/lib/python3.8/site-packages/flask/app.py", line 2051, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/benc/Workspaces/microblog/.venv-microblog/lib/python3.8/site-packages/flask/app.py", line 1501, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/benc/Workspaces/microblog/.venv-microblog/lib/python3.8/site-packages/flask/app.py", line 1499, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/benc/Workspaces/microblog/.venv-microblog/lib/python3.8/site-packages/flask/app.py", line 1485, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/benc/Workspaces/microblog/.venv-microblog/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/benc/Workspaces/microblog/app/routes.py", line 31, in index
    return render_template('index.html',title='Home Page', form=form, posts=posts)
  File "/home/benc/Workspaces/microblog/.venv-microblog/lib/python3.8/site-packages/flask/templating.py", line 148, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/benc/Workspaces/microblog/.venv-microblog/lib/python3.8/site-packages/jinja2/environment.py", line 1068, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/benc/Workspaces/microblog/.venv-microblog/lib/python3.8/site-packages/jinja2/environment.py", line 997, in get_template
    return self._load_template(name, globals)
  File "/home/benc/Workspaces/microblog/.venv-microblog/lib/python3.8/site-packages/jinja2/environment.py", line 958, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/benc/Workspaces/microblog/.venv-microblog/lib/python3.8/site-packages/jinja2/loaders.py", line 137, in load
    code = environment.compile(source, name, filename)
  File "/home/benc/Workspaces/microblog/.venv-microblog/lib/python3.8/site-packages/jinja2/environment.py", line 757, in compile
    self.handle_exception(source=source_hint)
  File "/home/benc/Workspaces/microblog/.venv-microblog/lib/python3.8/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/benc/Workspaces/microblog/app/templates/index.html", line 21, in template
    {% endblock %}
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'endblock'. You probably made a nesting mistake. Jinja is expecting this tag, but currently looking for 'elif' or 'else' or 'endif'. The innermost block that needs to be closed is 'if'.
2021-05-28 12:11:49,197 INFO: Microblog startup [in /home/benc/Workspaces/microblog/app/__init__.py:47]
2021-05-28 12:15:13,842 INFO: Microblog startup [in /home/benc/Workspaces/microblog/app/__init__.py:47]
2021-05-28 12:24:00,129 INFO: Microblog startup [in /home/benc/Workspaces/microblog/app/__init__.py:47]
2021-05-28 12:33:33,971 INFO: Microblog startup [in /home/benc/Workspaces/microblog/app/__init__.py:47]
2021-05-28 12:33:37,320 ERROR: Exception on /index [GET] [in /home/benc/Workspaces/microblog/.venv-microblog/lib/python3.8/site-packages/flask/app.py:1440]
Traceback (most recent call last):
  File "/home/benc/Workspaces/microblog/.venv-microblog/lib/python3.8/site-packages/flask/app.py", line 2051, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/benc/Workspaces/microblog/.venv-microblog/lib/python3.8/site-packages/flask/app.py", line 1501, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/benc/Workspaces/microblog/.venv-microblog/lib/python3.8/site-packages/flask/app.py", line 1499, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/benc/Workspaces/microblog/.venv-microblog/lib/python3.8/site-packages/flask/app.py", line 1485, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/benc/Workspaces/microblog/.venv-microblog/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/benc/Workspaces/microblog/app/routes.py", line 33, in index
    next_url = url_for('index', page=posts.netx_num) \
AttributeError: 'Pagination' object has no attribute 'netx_num'
2021-05-28 12:34:00,857 INFO: Microblog startup [in /home/benc/Workspaces/microblog/app/__init__.py:47]
2021-05-28 12:41:21,701 INFO: Microblog startup [in /home/benc/Workspaces/microblog/app/__init__.py:47]
2021-05-30 11:24:51,051 INFO: Microblog startup [in /home/benc/Workspaces/microblog/app/__init__.py:49]
2021-05-30 11:25:50,961 INFO: Microblog startup [in /home/benc/Workspaces/microblog/app/__init__.py:49]
2021-05-30 11:26:28,420 INFO: Microblog startup [in /home/benc/Workspaces/microblog/app/__init__.py:49]
2021-05-30 11:26:39,596 ERROR: Exception on /login [GET] [in /home/benc/Workspaces/microblog/.venv-microblog/lib/python3.8/site-packages/flask/app.py:1440]
Traceback (most recent call last):
  File "/home/benc/Workspaces/microblog/.venv-microblog/lib/python3.8/site-packages/flask/app.py", line 2051, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/benc/Workspaces/microblog/.venv-microblog/lib/python3.8/site-packages/flask/app.py", line 1501, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/benc/Workspaces/microblog/.venv-microblog/lib/python3.8/site-packages/flask/app.py", line 1499, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/benc/Workspaces/microblog/.venv-microblog/lib/python3.8/site-packages/flask/app.py", line 1485, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/benc/Workspaces/microblog/app/routes.py", line 72, in login
    return render_template('login.html', title='Sign In', form=form)
  File "/home/benc/Workspaces/microblog/.venv-microblog/lib/python3.8/site-packages/flask/templating.py", line 147, in render_template
    return _render(
  File "/home/benc/Workspaces/microblog/.venv-microblog/lib/python3.8/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/home/benc/Workspaces/microblog/.venv-microblog/lib/python3.8/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/home/benc/Workspaces/microblog/.venv-microblog/lib/python3.8/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/benc/Workspaces/microblog/app/templates/login.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/benc/Workspaces/microblog/app/templates/base.html", line 31, in top-level template code
    {% block content %}{% endblock %}
  File "/home/benc/Workspaces/microblog/app/templates/login.html", line 27, in block 'content'
    <a href="{{ url_for('resetn_password_request') }}">Click to reset it</a>
  File "/home/benc/Workspaces/microblog/.venv-microblog/lib/python3.8/site-packages/flask/helpers.py", line 334, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/benc/Workspaces/microblog/.venv-microblog/lib/python3.8/site-packages/flask/helpers.py", line 321, in url_for
    rv = url_adapter.build(
  File "/home/benc/Workspaces/microblog/.venv-microblog/lib/python3.8/site-packages/werkzeug/routing.py", line 2305, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'resetn_password_request'. Did you mean 'reset_password_request' instead?
